### ISSUE TITLE
Usar esse efeito.

### ISSUE THREAD

**Issue by ffabiorj** [MaiaVictor/heart#1]
Victor, bom dia.

Você saberia me dizer a forma de eu usar esse efeito ao invez de usar o coração, Eu usar letras de um nome próprio.

**Comment by VictorTaelin** [comment]
@ffabiorj para qualquer outra curva, 

1. Desenhe esta curva em uma imagem 512x512;

2. Edite o arquivo `heartField.json`, de modo que ele contenha um array de arrays, tal que, para quaisquer inteiros `0 <= i <= 511` e `0 <= j <= 511`, siga que `field[j][i]` (onde `field` é o valor do json) seja um array `[x,y]` de dois inteiros contendo o ponto mais próximo de `[i,j]` dentro da curva desejada.

**Comment by ffabiorj** [comment]
vlw man.
